# Generated by Django 3.1.7 on 2021-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('start_message_id', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, max_length=1024, null=True)),
                ('turn', models.IntegerField(blank=True, null=True)),
                ('chamber_position', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
