# Generated by Django 3.1.7 on 2021-03-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usergame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=1024, null=True)),
                ('turn_start_time', models.DateTimeField(blank=True, max_length=1024, null=True)),
                ('is_pending', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.user')),
            ],
            options={
                'db_table': 'usergames',
            },
        ),
    ]
