# Generated by Django 3.1.7 on 2021-03-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_usergame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergame',
            name='randfield',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
