# Generated by Django 3.1.7 on 2021-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210312_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='pending_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
